// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: testSTM32H750

#include "../ui.h"

void ui_comp_Label1_create_hook( lv_obj_t * comp)
{
}
