// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: testSTM32H750

#ifndef UI_DEBUGSCREEN_H
#define UI_DEBUGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DebugScreen
extern void ui_DebugScreen_screen_init(void);
extern void ui_DebugScreen_screen_destroy(void);
extern void ui_event_DebugScreen(lv_event_t *e);
extern lv_obj_t *ui_DebugScreen;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_labelBatteryVoltHigh;
extern lv_obj_t *ui_labelBatteryVoltAvg;
extern lv_obj_t *ui_labelBatteryVoltLow;
extern lv_obj_t *ui_labelBatteryTempHigh;
extern lv_obj_t *ui_labelBatteryTempAvg;
extern lv_obj_t *ui_labelBatteryTempLow;
extern lv_obj_t *ui_labelBatteryPowerHigh;
extern lv_obj_t *ui_labelBatteryPowerAvg;
extern lv_obj_t *ui_labelBatteryPowerLow;
extern lv_obj_t *ui_labelDebugSpeedHigh;
extern lv_obj_t *ui_labelDebugSpeedAvg;
extern lv_obj_t *ui_labelDebugSpeedLow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
