// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: testSTM32H750

#include "../ui.h"

lv_obj_t *ui_DebugScreen = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_labelBatteryVoltHigh = NULL;
lv_obj_t *ui_labelBatteryVoltAvg = NULL;
lv_obj_t *ui_labelBatteryVoltLow = NULL;
lv_obj_t *ui_labelBatteryTempHigh = NULL;
lv_obj_t *ui_labelBatteryTempAvg = NULL;
lv_obj_t *ui_labelBatteryTempLow = NULL;
lv_obj_t *ui_labelBatteryPowerHigh = NULL;
lv_obj_t *ui_labelBatteryPowerAvg = NULL;
lv_obj_t *ui_labelBatteryPowerLow = NULL;
lv_obj_t *ui_labelDebugSpeedHigh = NULL;
lv_obj_t *ui_labelDebugSpeedAvg = NULL;
lv_obj_t *ui_labelDebugSpeedLow = NULL;
// event funtions
void ui_event_DebugScreen(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_LONG_PRESSED) {
    _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MainScreen_screen_init);
  }
}

// build funtions

void ui_DebugScreen_screen_init(void) {
  ui_DebugScreen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_DebugScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(
      ui_DebugScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DebugScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image1 = lv_img_create(ui_DebugScreen);
  lv_img_set_src(ui_Image1, &ui_img_debugframe_png);
  lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 460
  lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 122
  lv_obj_set_x(ui_Image1, 0);
  lv_obj_set_y(ui_Image1, -1);
  lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_labelBatteryVoltHigh = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryVoltHigh, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryVoltHigh, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryVoltHigh, -25);
  lv_obj_set_y(ui_labelBatteryVoltHigh, -61);
  lv_obj_set_align(ui_labelBatteryVoltHigh, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryVoltHigh, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryVoltHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryVoltHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryVoltHigh, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryVoltAvg = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryVoltAvg, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryVoltAvg, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryVoltAvg, 80);
  lv_obj_set_y(ui_labelBatteryVoltAvg, -61);
  lv_obj_set_align(ui_labelBatteryVoltAvg, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryVoltAvg, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryVoltAvg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryVoltAvg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryVoltAvg, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryVoltLow = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryVoltLow, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryVoltLow, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryVoltLow, 176);
  lv_obj_set_y(ui_labelBatteryVoltLow, -61);
  lv_obj_set_align(ui_labelBatteryVoltLow, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryVoltLow, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryVoltLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryVoltLow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryVoltLow, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryTempHigh = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryTempHigh, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryTempHigh, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryTempHigh, -25);
  lv_obj_set_y(ui_labelBatteryTempHigh, -8);
  lv_obj_set_align(ui_labelBatteryTempHigh, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryTempHigh, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryTempHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryTempHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryTempHigh, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryTempAvg = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryTempAvg, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryTempAvg, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryTempAvg, 80);
  lv_obj_set_y(ui_labelBatteryTempAvg, -8);
  lv_obj_set_align(ui_labelBatteryTempAvg, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryTempAvg, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryTempAvg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryTempAvg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryTempAvg, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryTempLow = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryTempLow, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryTempLow, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryTempLow, 176);
  lv_obj_set_y(ui_labelBatteryTempLow, -8);
  lv_obj_set_align(ui_labelBatteryTempLow, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryTempLow, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryTempLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryTempLow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryTempLow, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryPowerHigh = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryPowerHigh, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryPowerHigh, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryPowerHigh, -25);
  lv_obj_set_y(ui_labelBatteryPowerHigh, 44);
  lv_obj_set_align(ui_labelBatteryPowerHigh, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryPowerHigh, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryPowerHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryPowerHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryPowerHigh, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryPowerAvg = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryPowerAvg, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryPowerAvg, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryPowerAvg, 80);
  lv_obj_set_y(ui_labelBatteryPowerAvg, 44);
  lv_obj_set_align(ui_labelBatteryPowerAvg, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryPowerAvg, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryPowerAvg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryPowerAvg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryPowerAvg, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryPowerLow = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelBatteryPowerLow, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryPowerLow, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryPowerLow, 176);
  lv_obj_set_y(ui_labelBatteryPowerLow, 44);
  lv_obj_set_align(ui_labelBatteryPowerLow, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryPowerLow, "0");
  lv_obj_set_style_text_color(
      ui_labelBatteryPowerLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryPowerLow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryPowerLow, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelDebugSpeedHigh = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelDebugSpeedHigh, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelDebugSpeedHigh, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelDebugSpeedHigh, -25);
  lv_obj_set_y(ui_labelDebugSpeedHigh, 95);
  lv_obj_set_align(ui_labelDebugSpeedHigh, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelDebugSpeedHigh, "0");
  lv_obj_set_style_text_color(
      ui_labelDebugSpeedHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelDebugSpeedHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelDebugSpeedHigh, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelDebugSpeedAvg = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelDebugSpeedAvg, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelDebugSpeedAvg, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelDebugSpeedAvg, 80);
  lv_obj_set_y(ui_labelDebugSpeedAvg, 95);
  lv_obj_set_align(ui_labelDebugSpeedAvg, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelDebugSpeedAvg, "0");
  lv_obj_set_style_text_color(
      ui_labelDebugSpeedAvg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelDebugSpeedAvg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelDebugSpeedAvg, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelDebugSpeedLow = lv_label_create(ui_DebugScreen);
  lv_obj_set_width(ui_labelDebugSpeedLow, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelDebugSpeedLow, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelDebugSpeedLow, 176);
  lv_obj_set_y(ui_labelDebugSpeedLow, 95);
  lv_obj_set_align(ui_labelDebugSpeedLow, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelDebugSpeedLow, "0");
  lv_obj_set_style_text_color(
      ui_labelDebugSpeedLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelDebugSpeedLow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelDebugSpeedLow, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_DebugScreen, ui_event_DebugScreen, LV_EVENT_ALL, NULL);
}

void ui_DebugScreen_screen_destroy(void) {
  if (ui_DebugScreen)
    lv_obj_del(ui_DebugScreen);

  // NULL screen variables
  ui_DebugScreen = NULL;
  ui_Image1 = NULL;
  ui_labelBatteryVoltHigh = NULL;
  ui_labelBatteryVoltAvg = NULL;
  ui_labelBatteryVoltLow = NULL;
  ui_labelBatteryTempHigh = NULL;
  ui_labelBatteryTempAvg = NULL;
  ui_labelBatteryTempLow = NULL;
  ui_labelBatteryPowerHigh = NULL;
  ui_labelBatteryPowerAvg = NULL;
  ui_labelBatteryPowerLow = NULL;
  ui_labelDebugSpeedHigh = NULL;
  ui_labelDebugSpeedAvg = NULL;
  ui_labelDebugSpeedLow = NULL;
}
