// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: testSTM32H750

#include "../ui.h"

lv_obj_t *ui_MainScreen = NULL;
lv_obj_t *ui_panelIMD = NULL;
lv_obj_t *ui_panelFault = NULL;
lv_obj_t *ui_panelRTD = NULL;
lv_obj_t *ui_panelTSAL = NULL;
lv_obj_t *ui_panelBSPD = NULL;
lv_obj_t *ui_panelSDC = NULL;
lv_obj_t *ui_panleReadyToDrive = NULL;
lv_obj_t *ui_panelDriveMode = NULL;
lv_obj_t *ui_labelSpeed = NULL;
lv_obj_t *ui_labelIMD = NULL;
lv_obj_t *ui_labelBatteryTemperature = NULL;
lv_obj_t *ui_labelPowerConsumption = NULL;
lv_obj_t *ui_labelBatteryLevel = NULL;
lv_obj_t *ui_labelFault = NULL;
lv_obj_t *ui_labelRTD = NULL;
lv_obj_t *ui_labelTSAL = NULL;
lv_obj_t *ui_labelBSPD = NULL;
lv_obj_t *ui_labelSDC = NULL;
lv_obj_t *ui_labelReadyToDrive = NULL;
lv_obj_t *ui_labelDriveMode = NULL;
lv_obj_t *ui_containerBattTemp = NULL;
lv_obj_t *ui_imgBattTempFill = NULL;
lv_obj_t *ui_imgBattTempKnob = NULL;
lv_obj_t *ui_imgBattTempIco = NULL;
lv_obj_t *ui_containerPowerConsumption = NULL;
lv_obj_t *ui_imgPowerConsumptionFill = NULL;
lv_obj_t *ui_imgPowerConsumptionKnob = NULL;
lv_obj_t *ui_imgPowerConsumptionIco = NULL;
lv_obj_t *ui_containerBattLevel = NULL;
lv_obj_t *ui_imgBattLevelFill = NULL;
lv_obj_t *ui_imgBattLevelKnob = NULL;
lv_obj_t *ui_imgBattLevelIco = NULL;

#define UI_MAINSCREEN_SLIDER_VALUE_MIN 1
#define UI_MAINSCREEN_SLIDER_VALUE_MAX 100
#define UI_MAINSCREEN_SLIDER_Y_MIN (-5)
#define UI_MAINSCREEN_SLIDER_Y_MAX (-147)

static int32_t ui_clamp_slider_value(int32_t value) {
  if (value < UI_MAINSCREEN_SLIDER_VALUE_MIN) {
    return UI_MAINSCREEN_SLIDER_VALUE_MIN;
  }

  if (value > UI_MAINSCREEN_SLIDER_VALUE_MAX) {
    return UI_MAINSCREEN_SLIDER_VALUE_MAX;
  }

  return value;
}

static int32_t ui_slider_value_to_y(int32_t value) {
  int32_t clamped = ui_clamp_slider_value(value);
  return UI_MAINSCREEN_SLIDER_Y_MIN +
         ((clamped - UI_MAINSCREEN_SLIDER_VALUE_MIN) *
          (UI_MAINSCREEN_SLIDER_Y_MAX - UI_MAINSCREEN_SLIDER_Y_MIN)) /
             (UI_MAINSCREEN_SLIDER_VALUE_MAX - UI_MAINSCREEN_SLIDER_VALUE_MIN);
}

static lv_color_t ui_temp_power_slider_color(int32_t value) {
  int32_t clamped = ui_clamp_slider_value(value);

  if (clamped <= 40) {
    return lv_color_hex(0x52BA00);
  }

  if (clamped <= 65) {
    return lv_color_hex(0xF4840D);
  }

  return lv_color_hex(0xF40D0D);
}

static lv_color_t ui_batt_level_slider_color(int32_t value) {
  int32_t clamped = ui_clamp_slider_value(value);

  if (clamped <= 40) {
    return lv_color_hex(0xF40D0D);
  }

  if (clamped <= 65) {
    return lv_color_hex(0xF4840D);
  }

  return lv_color_hex(0x52BA00);
}

static void ui_set_slider_image_color(lv_obj_t *fill, lv_obj_t *knob, lv_color_t color) {
  if (fill != NULL) {
    lv_obj_set_style_img_recolor(fill, color, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(fill, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
  }

  if (knob != NULL) {
    lv_obj_set_style_img_recolor_opa(knob, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
  }
}

static void ui_set_slider_state(lv_obj_t *fill, lv_obj_t *knob, int32_t value, lv_color_t color) {
  if (knob == NULL) {
    return;
  }

  lv_obj_set_y(knob, ui_slider_value_to_y(value));
  ui_set_slider_image_color(fill, knob, color);
}

static void ui_set_speed_demo_value(int32_t value) {
  if (ui_labelSpeed == NULL) {
    return;
  }

  lv_label_set_text_fmt(ui_labelSpeed, "%d", (int)value);
}

static void ui_step_demo_slider_value(int32_t *value, int32_t *direction, int32_t step) {
  int32_t next_value = *value + (*direction * step);

  if (next_value >= UI_MAINSCREEN_SLIDER_VALUE_MAX) {
    next_value = UI_MAINSCREEN_SLIDER_VALUE_MAX;
    *direction = -1;
  } else if (next_value <= UI_MAINSCREEN_SLIDER_VALUE_MIN) {
    next_value = UI_MAINSCREEN_SLIDER_VALUE_MIN;
    *direction = 1;
  }

  *value = next_value;
}

static void ui_style_status_panel(lv_obj_t *obj) {
  lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(obj, lv_color_hex(0x52BA00), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_set_batt_temp_slider_value(int32_t value) {
  ui_set_slider_state(
      ui_imgBattTempFill, ui_imgBattTempKnob, value, ui_temp_power_slider_color(value));
}

void ui_set_power_consumption_slider_value(int32_t value) {
  ui_set_slider_state(ui_imgPowerConsumptionFill,
                      ui_imgPowerConsumptionKnob,
                      value,
                      ui_temp_power_slider_color(value));
}

void ui_set_batt_level_slider_value(int32_t value) {
  ui_set_slider_state(
      ui_imgBattLevelFill, ui_imgBattLevelKnob, value, ui_batt_level_slider_color(value));
}

void ui_show_main_screen_slider_demo(void) {
  ui_set_speed_demo_value(120);
  ui_set_batt_temp_slider_value(80);
  ui_set_power_consumption_slider_value(50);
  ui_set_batt_level_slider_value(90);
}

void ui_step_main_screen_slider_demo(void) {
  static uint32_t last_update_ms = 0;
  static int32_t speed_value = 120;
  static int32_t speed_direction = 1;
  static int32_t batt_temp_value = 80;
  static int32_t batt_temp_direction = -1;
  static int32_t power_value = 50;
  static int32_t power_direction = 1;
  static int32_t batt_level_value = 90;
  static int32_t batt_level_direction = -1;
  uint32_t now = lv_tick_get();

  if ((now - last_update_ms) < 40U) {
    return;
  }

  last_update_ms = now;

  ui_step_demo_slider_value(&speed_value, &speed_direction, 1);
  ui_step_demo_slider_value(&batt_temp_value, &batt_temp_direction, 1);
  ui_step_demo_slider_value(&power_value, &power_direction, 2);
  ui_step_demo_slider_value(&batt_level_value, &batt_level_direction, 1);

  ui_set_speed_demo_value(speed_value);
  ui_set_batt_temp_slider_value(batt_temp_value);
  ui_set_power_consumption_slider_value(power_value);
  ui_set_batt_level_slider_value(batt_level_value);
}

// event funtions
void ui_event_MainScreen(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_LONG_PRESSED) {
    _ui_screen_change(
        &ui_DebugScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_DebugScreen_screen_init);
  }
}

// build funtions

void ui_MainScreen_screen_init(void) {
  ui_MainScreen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  // lv_obj_set_style_radius(ui_MainScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_panelIMD = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelIMD, 50);
  lv_obj_set_height(ui_panelIMD, 22);
  lv_obj_set_x(ui_panelIMD, 203);
  lv_obj_set_y(ui_panelIMD, -68);
  lv_obj_set_align(ui_panelIMD, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelIMD, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelIMD);

  ui_panelFault = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelFault, 50);
  lv_obj_set_height(ui_panelFault, 22);
  lv_obj_set_x(ui_panelFault, 203);
  lv_obj_set_y(ui_panelFault, -36);
  lv_obj_set_align(ui_panelFault, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelFault, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelFault);

  ui_panelRTD = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelRTD, 50);
  lv_obj_set_height(ui_panelRTD, 22);
  lv_obj_set_x(ui_panelRTD, 203);
  lv_obj_set_y(ui_panelRTD, -4);
  lv_obj_set_align(ui_panelRTD, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelRTD, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelRTD);

  ui_panelTSAL = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelTSAL, 50);
  lv_obj_set_height(ui_panelTSAL, 22);
  lv_obj_set_x(ui_panelTSAL, 203);
  lv_obj_set_y(ui_panelTSAL, 28);
  lv_obj_set_align(ui_panelTSAL, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelTSAL, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelTSAL);

  ui_panelBSPD = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelBSPD, 50);
  lv_obj_set_height(ui_panelBSPD, 22);
  lv_obj_set_x(ui_panelBSPD, 203);
  lv_obj_set_y(ui_panelBSPD, 60);
  lv_obj_set_align(ui_panelBSPD, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelBSPD, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelBSPD);

  ui_panelSDC = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelSDC, 50);
  lv_obj_set_height(ui_panelSDC, 22);
  lv_obj_set_x(ui_panelSDC, 203);
  lv_obj_set_y(ui_panelSDC, 92);
  lv_obj_set_align(ui_panelSDC, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelSDC, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelSDC);

  ui_panleReadyToDrive = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panleReadyToDrive, 120);
  lv_obj_set_height(ui_panleReadyToDrive, 27);
  lv_obj_set_x(ui_panleReadyToDrive, 164);
  lv_obj_set_y(ui_panleReadyToDrive, -117);
  lv_obj_set_align(ui_panleReadyToDrive, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panleReadyToDrive, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panleReadyToDrive);

  ui_panelDriveMode = lv_obj_create(ui_MainScreen);
  lv_obj_set_width(ui_panelDriveMode, 43);
  lv_obj_set_height(ui_panelDriveMode, 27);
  lv_obj_set_x(ui_panelDriveMode, -199);
  lv_obj_set_y(ui_panelDriveMode, -117);
  lv_obj_set_align(ui_panelDriveMode, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelDriveMode, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  ui_style_status_panel(ui_panelDriveMode);

  ui_labelSpeed = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelSpeed, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelSpeed, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelSpeed, -20);
  lv_obj_set_y(ui_labelSpeed, -101);
  lv_obj_set_align(ui_labelSpeed, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelSpeed, "120");
  lv_obj_set_style_text_color(
      ui_labelSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelSpeed, &ui_font_TomorrowBoldItalic64, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelIMD = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelIMD, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelIMD, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelIMD, 203);
  lv_obj_set_y(ui_labelIMD, -69);
  lv_obj_set_align(ui_labelIMD, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelIMD, "IMD");
  lv_obj_set_style_text_color(ui_labelIMD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelIMD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelIMD, &ui_font_TomorrowBoldItalic14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryTemperature = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelBatteryTemperature, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryTemperature, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryTemperature, -137);
  lv_obj_set_y(ui_labelBatteryTemperature, 116);
  lv_obj_set_align(ui_labelBatteryTemperature, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryTemperature, "TEMP");
  lv_obj_set_style_text_color(
      ui_labelBatteryTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryTemperature, &ui_font_TomorrowBoldItalic18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelPowerConsumption = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelPowerConsumption, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelPowerConsumption, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelPowerConsumption, -9);
  lv_obj_set_y(ui_labelPowerConsumption, 118);
  lv_obj_set_align(ui_labelPowerConsumption, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelPowerConsumption, "PWR kWh");
  lv_obj_set_style_text_color(
      ui_labelPowerConsumption, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelPowerConsumption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelPowerConsumption, &ui_font_TomorrowBoldItalic18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBatteryLevel = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelBatteryLevel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBatteryLevel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBatteryLevel, 111);
  lv_obj_set_y(ui_labelBatteryLevel, 115);
  lv_obj_set_align(ui_labelBatteryLevel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBatteryLevel, "BATT %");
  lv_obj_set_style_text_color(
      ui_labelBatteryLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBatteryLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBatteryLevel, &ui_font_TomorrowBoldItalic18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelFault = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelFault, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelFault, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelFault, 203);
  lv_obj_set_y(ui_labelFault, -37);
  lv_obj_set_align(ui_labelFault, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelFault, "FAULT");
  lv_obj_set_style_text_color(
      ui_labelFault, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelFault, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelFault, &ui_font_TomorrowBoldItalic14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelRTD = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelRTD, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelRTD, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelRTD, 203);
  lv_obj_set_y(ui_labelRTD, -5);
  lv_obj_set_align(ui_labelRTD, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelRTD, "RTD");
  lv_obj_set_style_text_color(ui_labelRTD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelRTD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelRTD, &ui_font_TomorrowBoldItalic14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelTSAL = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelTSAL, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelTSAL, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelTSAL, 203);
  lv_obj_set_y(ui_labelTSAL, 27);
  lv_obj_set_align(ui_labelTSAL, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelTSAL, "TSAL");
  lv_obj_set_style_text_color(
      ui_labelTSAL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelTSAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelTSAL, &ui_font_TomorrowBoldItalic14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelBSPD = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelBSPD, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelBSPD, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelBSPD, 203);
  lv_obj_set_y(ui_labelBSPD, 59);
  lv_obj_set_align(ui_labelBSPD, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelBSPD, "BSPB");
  lv_obj_set_style_text_color(
      ui_labelBSPD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelBSPD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelBSPD, &ui_font_TomorrowBoldItalic14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelSDC = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelSDC, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelSDC, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelSDC, 203);
  lv_obj_set_y(ui_labelSDC, 91);
  lv_obj_set_align(ui_labelSDC, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelSDC, "SDC");
  lv_obj_set_style_text_color(ui_labelSDC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelSDC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelSDC, &ui_font_TomorrowBoldItalic14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelReadyToDrive = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelReadyToDrive, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelReadyToDrive, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelReadyToDrive, 164);
  lv_obj_set_y(ui_labelReadyToDrive, -117);
  lv_obj_set_align(ui_labelReadyToDrive, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelReadyToDrive, "READY TO DRIVE");
  lv_obj_set_style_text_color(
      ui_labelReadyToDrive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelReadyToDrive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelReadyToDrive, &ui_font_TomorrowBoldItalic12, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelDriveMode = lv_label_create(ui_MainScreen);
  lv_obj_set_width(ui_labelDriveMode, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelDriveMode, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelDriveMode, -199);
  lv_obj_set_y(ui_labelDriveMode, -118);
  lv_obj_set_align(ui_labelDriveMode, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelDriveMode, "N");
  lv_obj_set_style_text_color(
      ui_labelDriveMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelDriveMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelDriveMode, &ui_font_TomorrowBoldItalic26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_containerBattTemp = lv_obj_create(ui_MainScreen);
  lv_obj_remove_style_all(ui_containerBattTemp);
  lv_obj_set_width(ui_containerBattTemp, 66);
  lv_obj_set_height(ui_containerBattTemp, 162);
  lv_obj_set_x(ui_containerBattTemp, -133);
  lv_obj_set_y(ui_containerBattTemp, 20);
  lv_obj_set_align(ui_containerBattTemp, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_containerBattTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_imgBattTempFill = lv_img_create(ui_containerBattTemp);
  lv_img_set_src(ui_imgBattTempFill, &ui_img_rectangle_27_png);
  lv_obj_set_width(ui_imgBattTempFill, LV_SIZE_CONTENT);  /// 62
  lv_obj_set_height(ui_imgBattTempFill, LV_SIZE_CONTENT); /// 157
  lv_obj_set_x(ui_imgBattTempFill, 0);
  lv_obj_set_y(ui_imgBattTempFill, -1);
  lv_obj_set_align(ui_imgBattTempFill, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgBattTempFill, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgBattTempFill, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_img_recolor(
      ui_imgBattTempFill, lv_color_hex(0x03FC15), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_img_recolor_opa(ui_imgBattTempFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_imgBattTempKnob = lv_img_create(ui_containerBattTemp);
  lv_img_set_src(ui_imgBattTempKnob, &ui_img_subtract_png);
  lv_obj_set_width(ui_imgBattTempKnob, LV_SIZE_CONTENT);  /// 62
  lv_obj_set_height(ui_imgBattTempKnob, LV_SIZE_CONTENT); /// 150
  lv_obj_set_x(ui_imgBattTempKnob, 0);
  lv_obj_set_y(ui_imgBattTempKnob, -20);
  lv_obj_set_align(ui_imgBattTempKnob, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgBattTempKnob, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgBattTempKnob, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_imgBattTempIco = lv_img_create(ui_containerBattTemp);
  lv_img_set_src(ui_imgBattTempIco, &ui_img_rectangle_24_png);
  lv_obj_set_width(ui_imgBattTempIco, LV_SIZE_CONTENT);  /// 66
  lv_obj_set_height(ui_imgBattTempIco, LV_SIZE_CONTENT); /// 161
  lv_obj_set_x(ui_imgBattTempIco, 0);
  lv_obj_set_y(ui_imgBattTempIco, -1);
  lv_obj_set_align(ui_imgBattTempIco, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgBattTempIco, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgBattTempIco, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_containerPowerConsumption = lv_obj_create(ui_MainScreen);
  lv_obj_remove_style_all(ui_containerPowerConsumption);
  lv_obj_set_width(ui_containerPowerConsumption, 66);
  lv_obj_set_height(ui_containerPowerConsumption, 162);
  lv_obj_set_x(ui_containerPowerConsumption, -10);
  lv_obj_set_y(ui_containerPowerConsumption, 20);
  lv_obj_set_align(ui_containerPowerConsumption, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_containerPowerConsumption,
                    LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_imgPowerConsumptionFill = lv_img_create(ui_containerPowerConsumption);
  lv_img_set_src(ui_imgPowerConsumptionFill, &ui_img_rectangle_27_png);
  lv_obj_set_width(ui_imgPowerConsumptionFill, LV_SIZE_CONTENT);  /// 62
  lv_obj_set_height(ui_imgPowerConsumptionFill, LV_SIZE_CONTENT); /// 157
  lv_obj_set_x(ui_imgPowerConsumptionFill, 0);
  lv_obj_set_y(ui_imgPowerConsumptionFill, -1);
  lv_obj_set_align(ui_imgPowerConsumptionFill, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgPowerConsumptionFill, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgPowerConsumptionFill, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_img_recolor(
      ui_imgPowerConsumptionFill, lv_color_hex(0x03FC15), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_img_recolor_opa(
      ui_imgPowerConsumptionFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_imgPowerConsumptionKnob = lv_img_create(ui_containerPowerConsumption);
  lv_img_set_src(ui_imgPowerConsumptionKnob, &ui_img_subtract_png);
  lv_obj_set_width(ui_imgPowerConsumptionKnob, LV_SIZE_CONTENT);  /// 62
  lv_obj_set_height(ui_imgPowerConsumptionKnob, LV_SIZE_CONTENT); /// 150
  lv_obj_set_x(ui_imgPowerConsumptionKnob, 0);
  lv_obj_set_y(ui_imgPowerConsumptionKnob, -147);
  lv_obj_set_align(ui_imgPowerConsumptionKnob, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgPowerConsumptionKnob, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgPowerConsumptionKnob, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_imgPowerConsumptionIco = lv_img_create(ui_containerPowerConsumption);
  lv_img_set_src(ui_imgPowerConsumptionIco, &ui_img_rectangle_24_png);
  lv_obj_set_width(ui_imgPowerConsumptionIco, LV_SIZE_CONTENT);  /// 66
  lv_obj_set_height(ui_imgPowerConsumptionIco, LV_SIZE_CONTENT); /// 161
  lv_obj_set_x(ui_imgPowerConsumptionIco, 0);
  lv_obj_set_y(ui_imgPowerConsumptionIco, -1);
  lv_obj_set_align(ui_imgPowerConsumptionIco, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgPowerConsumptionIco, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgPowerConsumptionIco, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_containerBattLevel = lv_obj_create(ui_MainScreen);
  lv_obj_remove_style_all(ui_containerBattLevel);
  lv_obj_set_width(ui_containerBattLevel, 66);
  lv_obj_set_height(ui_containerBattLevel, 162);
  lv_obj_set_x(ui_containerBattLevel, 113);
  lv_obj_set_y(ui_containerBattLevel, 20);
  lv_obj_set_align(ui_containerBattLevel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_containerBattLevel,
                    LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_imgBattLevelFill = lv_img_create(ui_containerBattLevel);
  lv_img_set_src(ui_imgBattLevelFill, &ui_img_rectangle_27_png);
  lv_obj_set_width(ui_imgBattLevelFill, LV_SIZE_CONTENT);  /// 62
  lv_obj_set_height(ui_imgBattLevelFill, LV_SIZE_CONTENT); /// 157
  lv_obj_set_x(ui_imgBattLevelFill, 0);
  lv_obj_set_y(ui_imgBattLevelFill, -1);
  lv_obj_set_align(ui_imgBattLevelFill, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgBattLevelFill, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgBattLevelFill, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_img_recolor(
      ui_imgBattLevelFill, lv_color_hex(0x03FC15), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_img_recolor_opa(ui_imgBattLevelFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_imgBattLevelKnob = lv_img_create(ui_containerBattLevel);
  lv_img_set_src(ui_imgBattLevelKnob, &ui_img_subtract_png);
  lv_obj_set_width(ui_imgBattLevelKnob, LV_SIZE_CONTENT);  /// 62
  lv_obj_set_height(ui_imgBattLevelKnob, LV_SIZE_CONTENT); /// 150
  lv_obj_set_x(ui_imgBattLevelKnob, 0);
  lv_obj_set_y(ui_imgBattLevelKnob, -147);
  lv_obj_set_align(ui_imgBattLevelKnob, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgBattLevelKnob, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgBattLevelKnob, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_imgBattLevelIco = lv_img_create(ui_containerBattLevel);
  lv_img_set_src(ui_imgBattLevelIco, &ui_img_rectangle_24_png);
  lv_obj_set_width(ui_imgBattLevelIco, LV_SIZE_CONTENT);  /// 66
  lv_obj_set_height(ui_imgBattLevelIco, LV_SIZE_CONTENT); /// 161
  lv_obj_set_x(ui_imgBattLevelIco, 0);
  lv_obj_set_y(ui_imgBattLevelIco, -1);
  lv_obj_set_align(ui_imgBattLevelIco, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgBattLevelIco, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_imgBattLevelIco, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

  ui_show_main_screen_slider_demo();
}

void ui_MainScreen_screen_destroy(void) {
  if (ui_MainScreen)
    lv_obj_del(ui_MainScreen);

  // NULL screen variables
  ui_MainScreen = NULL;
  ui_panelIMD = NULL;
  ui_panelFault = NULL;
  ui_panelRTD = NULL;
  ui_panelTSAL = NULL;
  ui_panelBSPD = NULL;
  ui_panelSDC = NULL;
  ui_panleReadyToDrive = NULL;
  ui_panelDriveMode = NULL;
  ui_labelSpeed = NULL;
  ui_labelIMD = NULL;
  ui_labelBatteryTemperature = NULL;
  ui_labelPowerConsumption = NULL;
  ui_labelBatteryLevel = NULL;
  ui_labelFault = NULL;
  ui_labelRTD = NULL;
  ui_labelTSAL = NULL;
  ui_labelBSPD = NULL;
  ui_labelSDC = NULL;
  ui_labelReadyToDrive = NULL;
  ui_labelDriveMode = NULL;
  ui_containerBattTemp = NULL;
  ui_imgBattTempFill = NULL;
  ui_imgBattTempKnob = NULL;
  ui_imgBattTempIco = NULL;
  ui_containerPowerConsumption = NULL;
  ui_imgPowerConsumptionFill = NULL;
  ui_imgPowerConsumptionKnob = NULL;
  ui_imgPowerConsumptionIco = NULL;
  ui_containerBattLevel = NULL;
  ui_imgBattLevelFill = NULL;
  ui_imgBattLevelKnob = NULL;
  ui_imgBattLevelIco = NULL;
}
