// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: testSTM32H750

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t *e);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_panelIMD;
extern lv_obj_t *ui_panelFault;
extern lv_obj_t *ui_panelRTD;
extern lv_obj_t *ui_panelTSAL;
extern lv_obj_t *ui_panelBSPD;
extern lv_obj_t *ui_panelSDC;
extern lv_obj_t *ui_panleReadyToDrive;
extern lv_obj_t *ui_panelDriveMode;
extern lv_obj_t *ui_labelSpeed;
extern lv_obj_t *ui_labelIMD;
extern lv_obj_t *ui_labelBatteryTemperature;
extern lv_obj_t *ui_labelPowerConsumption;
extern lv_obj_t *ui_labelBatteryLevel;
extern lv_obj_t *ui_labelFault;
extern lv_obj_t *ui_labelRTD;
extern lv_obj_t *ui_labelTSAL;
extern lv_obj_t *ui_labelBSPD;
extern lv_obj_t *ui_labelSDC;
extern lv_obj_t *ui_labelReadyToDrive;
extern lv_obj_t *ui_labelDriveMode;
extern lv_obj_t *ui_containerBattTemp;
extern lv_obj_t *ui_imgBattTempFill;
extern lv_obj_t *ui_imgBattTempKnob;
extern lv_obj_t *ui_imgBattTempIco;
extern lv_obj_t *ui_containerPowerConsumption;
extern lv_obj_t *ui_imgPowerConsumptionFill;
extern lv_obj_t *ui_imgPowerConsumptionKnob;
extern lv_obj_t *ui_imgPowerConsumptionIco;
extern lv_obj_t *ui_containerBattLevel;
extern lv_obj_t *ui_imgBattLevelFill;
extern lv_obj_t *ui_imgBattLevelKnob;
extern lv_obj_t *ui_imgBattLevelIco;
// CUSTOM VARIABLES
void ui_set_batt_temp_slider_value(int32_t value);
void ui_set_power_consumption_slider_value(int32_t value);
void ui_set_batt_level_slider_value(int32_t value);
void ui_show_main_screen_slider_demo(void);
void ui_step_main_screen_slider_demo(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
