// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: testSTM32H750

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image1 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image1, &ui_img_frame_1_png);
  lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 480
  lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 272
  lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
}

void ui_Screen1_screen_destroy(void) {
  if (ui_Screen1)
    lv_obj_del(ui_Screen1);

  // NULL screen variables
  ui_Screen1 = NULL;
  ui_Image1 = NULL;
}
