// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: testSTM32H750

#ifndef _TESTSTM32H750_UI_H
#define _TESTSTM32H750_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_MainScreen.h"
#include "screens/ui_DebugScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rectangle_27_png); // assets/Rectangle 27.png
LV_IMG_DECLARE(ui_img_subtract_png);     // assets/Subtract.png
LV_IMG_DECLARE(ui_img_rectangle_24_png); // assets/Rectangle 24.png
LV_IMG_DECLARE(ui_img_debugframe_png);   // assets/DebugFrame.png

// FONTS
LV_FONT_DECLARE(ui_font_TomorrowBoldItalic12);
LV_FONT_DECLARE(ui_font_TomorrowBoldItalic14);
LV_FONT_DECLARE(ui_font_TomorrowBoldItalic18);
LV_FONT_DECLARE(ui_font_TomorrowBoldItalic26);
LV_FONT_DECLARE(ui_font_TomorrowBoldItalic64);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
