// This file was generated by SquareLine Studio and trimmed to the helpers
// required by the current UI export.

#ifndef _TESTSTM32H750_UI_HELPERS_H
#define _TESTSTM32H750_UI_HELPERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
